#!/bin/sh

cd /var/jb
if [ "$1" = "upgrade" ]; then
    launchctl unload /var/jb/Library/LaunchDaemons/com.xxdevice.ctwsrv.plist
fi

killall -9 "CTW Pro"

#chmod -R 0755 "/Applications/CTW Pro.app"
chmod a+wrxs "/var/jb/Applications/CTW Pro.app/CTW Pro"

#if [ -d /var/db/CTW  ];then
#   mv /var/db/CTW /var/mobile/
#fi

if [ ! -d /var/jb/var/mobile/CTW  ];then
    mkdir /var/jb/var/mobile/CTW
    mkdir /var/jb/var/mobile/CTW/backup
fi

chown -R mobile:mobile /var/jb/var/mobile/CTW
chmod -R 777 /var/jb/var/mobile/CTW

chown mobile:mobile /var/mobile/Media/CTWExport
chown mobile:mobile /var/mobile/Media/CTWImport
        
mkdir -p /var/jb/var/root/Documents

chown root:wheel /var/jb/usr/bin/ctwsrv
chmod 755 /var/jb/usr/bin/ctwsrv
chown root:wheel /var/jb/Library/LaunchDaemons/com.xxdevice.ctwsrv.plist
chmod 644 /var/jb/Library/LaunchDaemons/com.xxdevice.ctwsrv.plist

launchctl load /var/jb/Library/LaunchDaemons/com.xxdevice.ctwsrv.plist

killall configd

exit 0
