#!/bin/bash
echo "Remove old files..."
killall -9 VBox >/dev/null 2>&1 || true
killall -9 VBox_ >/dev/null 2>&1 || true

if [ -d "/Applications/VBox.app" ]; then
	rm -rf "/Applications/VBox.app" >/dev/null 2>&1
fi

rm -f \
	"/Library/MobileSubstrate/DynamicLibraries/VBox.dylib" \
	"/Library/MobileSubstrate/DynamicLibraries/VBox.plist" \
	"/Library/MobileSubstrate/DynamicLibraries/VBoc.dylib" \
	"/Library/MobileSubstrate/DynamicLibraries/VBoc.plist" \
	"/var/jb/var/mobile/Library/Preferences/VBox/vv.plist" \
	>/dev/null 2>&1

exit 0
